### PR TITLE
in atlas-collection, always build lcmtypes, state sync, and bdi walking

### LINKED ISSUE #116: Atlas lcmtypes error when building w/o atlas_drivers external
I am trying to build OH without access to the atlas_drivers external (but have access to SNOPT and built gurobi on its own) and am getting the following errors:

> [ 14%] Building CXX object src/CMakeFiles/AtlasFallDetector.dir/AtlasFallDetector.cpp.o
> In file included from /home/rc/oh-distro/software/control/src/AtlasFallDetector.cpp:1:0:
> /home/rc/oh-distro/software/control/src/AtlasFallDetector.hpp:12:39: fatal error: lcmtypes/atlas/status_t.hpp: No such file or directory
>  #include "lcmtypes/atlas/status_t.hpp"
>                                        ^
> compilation terminated.
> make[4]: *** [src/CMakeFiles/AtlasFallDetector.dir/AtlasFallDetector.cpp.o] Error 1
> make[3]: *** [src/CMakeFiles/AtlasFallDetector.dir/all] Error 2
> make[2]: *** [all] Error 2
> make[1]: *** [all] Error 2
> make: *** [all] Error 2

I tried cd'ing into drc_lcmtypes, doing a make clean, then make again in /software. That didn't work.

### PR DESCRIPTION
**Pull request by patmarion**
fixes #116

### CODE REVIEW

**Comment by patmarion** [comment]
@wxmerkt can you take a look?

@mauricefallon note this PR is against oh-distro to fix the open source build.  after merging this PR, then oh-distro/master could be merged into oh-distro-private/master, if you think that's a reasonable workflow

**Comment by wxmerkt** [comment]
Looks good to me :+1:

**Comment by mauricefallon** [comment]
This is fine: we just build a few minor modules.

But it does go back on the push to not-require atlas-specific code. I'm happy to come back to that in future

**Comment by patmarion** [comment]
@wxmerkt have you seen this build error on travic-ci?  Is travis-ci supposed to work for the oh-distro/master branch right now?

https://travis-ci.org/openhumanoids/oh-distro/builds/117984236

**Comment by wxmerkt** [comment]
@patmarion Travis is working. The state-sync-atlas requires atlas to be build, cf. https://github.com/oh-dev/oh-distro/blob/fix-atlas-collection-build/software/atlas-collection/state_sync_atlas/src/state_sync_atlas/CMakeLists.txt#L17

**Comment by mauricefallon** [comment]
Atlas driver is needed for this, you will need to move it back in behind BUILD_ATLAS_DRIVER

https://github.com/oh-dev/oh-distro/blob/fix-atlas-collection-build/software/atlas-collection/state_sync_atlas/src/state_sync_atlas/state_sync.cpp#L69

**Comment by patmarion** [comment]
Ah, bummer.  I'll move that back.

In the future, maybe I can remove the dependency on the atlas driver?  I think the atlas state sync process is required to run the Atlas drake simulator?

**Comment by mauricefallon** [comment]
No, moving state sync back into private is fine. It's not used in simulation. We don't do state estimation in the simulator. Its purpose is to stick all the joints together into EST_ROBOT_STATE but most of its code is due to the calibration.

BTW: @gizatt  Pronto works just fine with IHMC's simulator ... so maybe state estimation could be supported with drake-sim for Val/Atlas? We've cleaned up things quite well since the Finals.

**Pull request merged**
